Repository alibaba/EasyCV, pull requests merged in 2022-04, with the labels that each got.

#10 update moby pretrained model to deit small
  benchmarks/selfsup/classification/imagenet/moby_deit_small_p16_8xb2048_30e_feature.py
  configs/selfsup/moby/moby_deit_small_p16_4xb128_300e_tfrecord.py
  docs/source/model_zoo_ssl.md
Labels: enhancement

#13 Refine auto release workflow
  .github/workflows/publish.yaml
  setup.py
Labels: github workflow

#14 [doc] update readme doc and changelog
  .github/workflows/citest.yaml
  .github/workflows/publish.yaml
  README.md
  docs/source/_static/dingding_qrcode.jpg
  docs/source/change_log.md
  setup.py
Labels: documentation

#19 Fix: classifier run inference error
  docs/source/quick_start.md
  easycv/apis/export.py
  easycv/models/heads/cls_head.py
  tests/apis/test_export.py
Labels: bug

#22 add notebook tutorials
  .github/workflows/citest.yaml
  README.md
  docs/source/tutorials/EasyCV 图像分类resnet50.ipynb
  docs/source/tutorials/EasyCV 图像分类swinTransformer.ipynb
  docs/source/tutorials/EasyCV 图像检测YoloX.ipynb
  docs/source/tutorials/EasyCV 自监督训练-dino.ipynb
  docs/source/tutorials/EasyCV 自监督训练-moco.ipynb
  requirements.txt
Labels: documentation

#20 compression tutorial
  docs/source/tutorials/compression.md
Labels: documentation

#31 Fix/third transforms warpper
  easycv/datasets/shared/pipelines/third_transforms_wrapper.py
Labels: bug

#29 feat: readthedocs support & tutorial docs refinement
  .readthedocs.yaml
  README.md
  configs/classification/cifar10/r50_b128_300e_jpg.py
  configs/classification/cifar10/swintiny_b64_5e_jpg.py
  docs/source/api/easycv.datasets.classification.pipelines.rst
  docs/source/api/easycv.datasets.detection.data_sources.rst
  docs/source/api/easycv.datasets.detection.pipelines.rst
  docs/source/api/easycv.datasets.shared.data_sources.rst
  docs/source/api/easycv.datasets.shared.pipelines.rst
  docs/source/api/easycv.hooks.rst
  docs/source/api/easycv.models.utils.rst
  docs/source/conf.py
  docs/source/model_zoo_cls.md
  docs/source/model_zoo_detection.md
  docs/source/model_zoo_ssl.md
  docs/source/tutorials/EasyCV 图像分类resnet50.ipynb
  docs/source/tutorials/EasyCV 图像分类swinTransformer.ipynb
  docs/source/tutorials/EasyCV 图像检测YoloX.ipynb
  docs/source/tutorials/EasyCV 自监督训练-dino.ipynb
  docs/source/tutorials/EasyCV 自监督训练-moco.ipynb
  docs/source/tutorials/cls.md
  docs/source/tutorials/compression.md
  docs/source/tutorials/ssl.md
  docs/source/tutorials/yolox.md
  easycv/datasets/shared/pipelines/third_transforms_wrapper.py
  requirements.txt
  requirements/optional.txt
  requirements/readthedocs.txt
  requirements/runtime.txt
Labels: documentation, github workflow

#23 fix multi-process reading of detection datasource and accelerate data preprocessing
  easycv/datasets/detection/data_sources/base.py
  easycv/datasets/detection/data_sources/pai_format.py
  easycv/datasets/detection/data_sources/raw.py
  easycv/datasets/detection/data_sources/voc.py
  easycv/datasets/shared/data_sources/concat.py
  tests/datasets/detection/data_sources/test_raw.py
  tests/datasets/detection/data_sources/test_voc.py
  tools/train.py
Labels: bug, enhancement

#39 [docs] add chinese readme
  README.md
  README_zh-CN.md
Labels: documentation

#46 [bugfix] fix gpu_collect error
  easycv/apis/train.py
  easycv/utils/test_util.py
  tests/tools/test_yolox_train.py
Labels: bug

#47 fix: add missing shell scripts
  .github/workflows/citest.yaml
  .gitignore
  .scripts/ci_test.sh
  .scripts/linter.sh
  benchmarks/tools/dist_extract.sh
  docs/build_docs.sh
  tools/dist_test.sh
  tools/dist_train.sh
  tools/kill.sh
  tools/prepare_data/prepare_voc07_cls.sh
Labels: bug
